-- 007_policies.sql — published legal content
--
-- Terms, privacy, refund, liability, consent, cancellation, delivery and
-- data-deletion text, plus the business details shown on invoices and policy
-- pages. Carried over from the previous system, where this content was written
-- once and exists nowhere else — the old migration files recreate the TABLES,
-- never the CONTENT.
--
-- Each policy is a list of clauses with a display order and a version, so text
-- can be revised without losing what an earlier customer agreed to.
--
-- Written to be safe to run against a database that already has these tables:
-- CREATE IF NOT EXISTS, and inserts that skip rows already present.
--
-- Meta checks the privacy-policy URL during app review and business
-- verification, so these must stay reachable.


CREATE TABLE IF NOT EXISTS terms_and_conditions (
    id smallint NOT NULL,
    title character varying(255) NOT NULL,
    description text NOT NULL,
    display_order smallint NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    modified_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    version character varying(20) DEFAULT '1.0'::character varying NOT NULL,
    effective_from date DEFAULT CURRENT_DATE NOT NULL
);
ALTER TABLE terms_and_conditions DROP CONSTRAINT IF EXISTS terms_and_conditions_pkey;
ALTER TABLE terms_and_conditions ADD CONSTRAINT terms_and_conditions_pkey PRIMARY KEY (id);
INSERT INTO terms_and_conditions (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('4', 'Permitted Use', 'The service is intended for lawful, personal and legitimate purposes — checking your own vehicle, performing due diligence before buying a pre-owned vehicle, or verifying details before selling a vehicle. Reports are for your own reference and must not be presented as an official Government document.', '4', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO terms_and_conditions (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('10', 'Suspension and Termination', 'We may suspend or terminate access without prior notice if we reasonably believe these terms have been breached, if the service is being misused, or if required by law or by a Government authority. Fees for reports already delivered are not refundable on termination for breach.', '10', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO terms_and_conditions (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('12', 'Governing Law and Jurisdiction', 'These Terms are governed by the laws of India. Any dispute arising out of or in connection with the service shall be subject to the exclusive jurisdiction of the courts at Bengaluru, Karnataka.', '12', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO terms_and_conditions (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('1', 'Acceptance of Terms', 'By using gaadipe.in, or any GaadiPe service or communication channel (including WhatsApp, SMS or email where offered), you agree to be bound by these Terms & Conditions. GaadiPe is operated by ServerPe App Solutions (GSTIN 29BSMPK7696H1ZT). If you do not agree with any part of these Terms, please do not use the service.', '1', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO terms_and_conditions (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('2', 'Description of Service', 'GaadiPe is an information service that retrieves vehicle documentation details — registration certificate (RC) and vehicle information, insurance validity, fitness, emission (PUCC), permits, FASTag status and traffic e-challans — from official Government of India data sources, and presents them to you as a consolidated report over WhatsApp.', '2', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO terms_and_conditions (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('3', 'Eligibility', 'You must be at least 18 years of age and capable of entering into a legally binding contract under the Indian Contract Act, 1872 to use this service. By using GaadiPe you confirm that you meet these requirements and that the information you provide is accurate.', '3', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO terms_and_conditions (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('5', 'Prohibited Use', 'You must not use GaadiPe for stalking, harassment, profiling, unsolicited marketing, debt recovery, building or reselling a database of vehicle or owner information, or any purpose prohibited by law. Automated scraping, resale of reports, reverse engineering, or attempts to bypass rate limits or authentication are strictly forbidden.', '5', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO terms_and_conditions (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('7', 'Fees, Plans and Payments', 'Certain reports are offered free of charge and others are paid, at the prices displayed at the time of purchase. All prices are in Indian Rupees and inclusive of applicable taxes unless stated otherwise. Payments are processed by our payment gateway partner; GaadiPe does not store your card, UPI or banking credentials.', '7', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO terms_and_conditions (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('9', 'Intellectual Property', 'The GaadiPe name, logo, report formats, layouts and software are the property of ServerPe App Solutions. The underlying vehicle data remains the property of the respective Government authorities. You may use reports for personal reference but may not reproduce our branding or report templates commercially.', '9', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO terms_and_conditions (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('11', 'Changes to These Terms', 'We may update these Terms from time to time. The version published on gaadipe.in at the time of your use governs that use. Continuing to use the service after an update constitutes acceptance of the revised Terms.', '11', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO terms_and_conditions (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('6', 'Accuracy of Information and Government Data Source', 'All vehicle particulars shown by GaadiPe are reproduced exactly as received from the Government of India''s backup/replica databases made available through the Unified Logistics Interface Platform (ULIP) — covering VAHAN, the e-Challan system and NETC FASTag. These replicas are synchronised periodically and may lag behind, or differ from, the live records held at the Regional Transport Office (RTO). GaadiPe does not create, alter, correct or independently verify this data. If any detail appears incorrect, outdated, incomplete or does not match your physical documents, please re-check directly with your local RTO or the concerned issuing authority.', '6', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 21:05:35.265254+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO terms_and_conditions (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('13', 'Discrepancies and Re-verification with the RTO', 'Where the information in a GaadiPe report does not match your Registration Certificate, insurance policy, PUCC, fitness certificate, permit or any other document, the Government record at your local Regional Transport Office prevails. You must approach the concerned RTO or issuing authority to inspect, correct or update the official record. GaadiPe has no authority to modify, correct, delete or dispute any Government record, and cannot process such corrections on your behalf.', '13', 't', '2026-08-13 21:05:35.265254+05:30', '2026-08-13 21:05:35.265254+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO terms_and_conditions (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('14', 'No Government Affiliation', 'GaadiPe is a private information service operated by ServerPe App Solutions. It is not affiliated with, endorsed by, sponsored by, or connected in any way to the Ministry of Road Transport and Highways, the National Informatics Centre, DPIIT, VAHAN, PARIVAHAN, any Regional Transport Office, or any other Government body or authority. All Government names, marks and platform names referred to are the property of their respective owners and are used only to describe the origin of the data. Reports issued by GaadiPe are private compilations and are not Government-issued documents.', '14', 't', '2026-08-13 21:06:55.237073+05:30', '2026-08-13 21:06:55.237073+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO terms_and_conditions (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('8', 'Service Availability', 'GaadiPe depends on authorized third-party and Government vehicle-data APIs, payment gateways, hosting, and the channels we use to communicate with you (SMS, email and, now or in future, WhatsApp). The service may be unavailable, delayed or degraded due to maintenance, upstream outages or events beyond our control. We do not guarantee uninterrupted availability.', '8', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO terms_and_conditions (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('15', 'GaadiPe on WhatsApp', 'GaadiPe now operates primarily through WhatsApp. You interact with GaadiPe by messaging our official WhatsApp business number; vehicle checks, reports, payments, the game and alerts are delivered in your WhatsApp chat and on secure web pages we link to. WhatsApp messages are delivered through Meta Platforms and are also subject to WhatsApp''s own terms.', '15', 't', '2026-08-24 16:02:12.482158+05:30', '2026-08-24 16:02:12.482158+05:30', '1.0', '2026-08-24') ON CONFLICT (id) DO NOTHING;
INSERT INTO terms_and_conditions (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('16', 'Premium Subscription', 'Premium is a paid, per-vehicle plan starting at Rs.99 for a 28-day term (the exact price may vary with the reward you earn in the game and is always shown before you pay, inclusive of GST). You may add up to five vehicles per mobile number, each with its own 28-day window. There is NO auto-charge and NO auto-renewal — Premium simply lapses at the end of its term unless you choose to renew. Premium includes the full vehicle report and automatic daily monitoring for the term.', '16', 't', '2026-08-24 16:02:12.482158+05:30', '2026-08-24 16:02:12.482158+05:30', '1.0', '2026-08-24') ON CONFLICT (id) DO NOTHING;
INSERT INTO terms_and_conditions (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('17', 'Free Trial', 'We may offer a free 7-day trial covering one vehicle, limited to one trial per mobile number. The trial provides monitoring alerts and access to the daily game for seven days, after which it ends automatically. No payment is taken for the trial.', '17', 't', '2026-08-24 16:02:12.482158+05:30', '2026-08-24 16:02:12.482158+05:30', '1.0', '2026-08-24') ON CONFLICT (id) DO NOTHING;
INSERT INTO terms_and_conditions (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('18', 'Vehicle Monitoring', 'For trial and Premium vehicles, GaadiPe periodically re-checks Government-sourced data and notifies you of new challans and of insurance, emission (PUCC), fitness and road-tax expiries. Monitoring is a best-effort convenience: source data may be delayed or incomplete, and GaadiPe does not guarantee that every event is detected or notified. Always verify important matters with the RTO or the relevant authority.', '18', 't', '2026-08-24 16:02:12.482158+05:30', '2026-08-24 16:02:12.482158+05:30', '1.0', '2026-08-24') ON CONFLICT (id) DO NOTHING;
INSERT INTO terms_and_conditions (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('19', 'Number-Plate Game', 'The number-plate game is a free game of skill. Playing costs nothing and requires no entry fee or stake. Rewards earned in the game are discounts on GaadiPe''s own Premium price only — they are not cash, are not withdrawable, and have no value outside GaadiPe. The game is not a lottery, betting or gambling activity.', '19', 't', '2026-08-24 16:02:12.482158+05:30', '2026-08-24 16:02:12.482158+05:30', '1.0', '2026-08-24') ON CONFLICT (id) DO NOTHING;
INSERT INTO terms_and_conditions (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('20', 'Number Plates Used in the Game', 'The plates shown in our number-plate game are real, publicly-visible registrations used for identification practice only. They appear without any owner or report information and are not associated with any account. If you believe a plate should not be shown, contact us and we will remove it.', '20', 't', '2026-08-24 16:02:12.502664+05:30', '2026-08-24 16:02:12.502664+05:30', '1.0', '2026-08-24') ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS privacy_policy (
    id smallint NOT NULL,
    title character varying(255) NOT NULL,
    description text NOT NULL,
    display_order smallint NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    modified_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    version character varying(20) DEFAULT '1.0'::character varying NOT NULL,
    effective_from date DEFAULT CURRENT_DATE NOT NULL
);
ALTER TABLE privacy_policy DROP CONSTRAINT IF EXISTS privacy_policy_pkey;
ALTER TABLE privacy_policy ADD CONSTRAINT privacy_policy_pkey PRIMARY KEY (id);
INSERT INTO privacy_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('4', 'Vehicle Data and Its Sources', 'Vehicle information is retrieved in real time from official Government of India systems through the Unified Logistics Interface Platform (ULIP), operated under DPIIT — covering VAHAN (registration), the e-Challan system, and NETC FASTag. We are a consumer of these records; we do not own, modify or maintain them.', '4', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO privacy_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('6', 'Legal Basis and Consent', 'We process your personal data on the basis of the consent you give by initiating a conversation and requesting a vehicle check, and where processing is necessary to perform the service you have paid for or to comply with a legal obligation. You may withdraw consent at any time as described in our consent policy.', '6', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO privacy_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('8', 'Data Security', 'Sensitive fields — including owner name, parentage, contact number, chassis number, engine number, financier and addresses — are encrypted at rest using AES-256-GCM. Data in transit is protected using HTTPS/TLS. Access to production systems is restricted, and searchable fields use keyed blind indexes rather than plaintext.', '8', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO privacy_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('9', 'Data Retention', 'Vehicle records are cached so that repeat checks are faster and cheaper. Conversation logs, reports and payment records are retained for as long as needed to provide the service and to meet statutory record-keeping obligations, after which they are deleted or anonymised.', '9', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO privacy_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('10', 'Your Rights', 'You may request access to the personal data we hold about you, request correction of inaccurate data, request erasure of your data, withdraw consent, or nominate another person to exercise your rights in the event of your death or incapacity. Requests can be raised on the same WhatsApp number or by email.', '10', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO privacy_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('16', 'Game Data', 'When you play the number-plate game we store your play sessions, scores and streaks to run the game, the leaderboard, and any Premium discount you earn.', '16', 't', '2026-08-24 16:02:12.482158+05:30', '2026-08-24 16:02:12.482158+05:30', '1.0', '2026-08-24') ON CONFLICT (id) DO NOTHING;
INSERT INTO privacy_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('11', 'Children''s Privacy', 'GaadiPe is not directed at children. We do not knowingly collect personal data from anyone under 18 years of age. If we learn that we have done so, we will delete it.', '11', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO privacy_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('12', 'Grievance Redressal', 'For any privacy question, complaint or data request, contact the Grievance Officer at ServerPe App Solutions using the support contact published on gaadipe.in. We aim to acknowledge every request promptly and resolve it within the timelines prescribed by law.', '12', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO privacy_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('13', 'Changes to This Policy', 'We may revise this policy as the service evolves or as the law changes. The current version is always available on gaadipe.in, and material changes will be notified through the service.', '13', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO privacy_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('1', 'Scope of This Policy', 'This policy explains what personal data GaadiPe collects when you use our website (gaadipe.in) and any channel we use to communicate with you (such as SMS, email and, now or in future, WhatsApp), why we collect it, how we protect it, and the rights available to you under the Digital Personal Data Protection Act, 2023.', '1', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO privacy_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('2', 'Information You Provide', 'When you use GaadiPe you provide your mobile number (verified by a one-time password), your name for the invoice, and the vehicle registration numbers you ask us to check. If you purchase a report you also provide the place of supply (state) for GST; payment details are handled directly by our payment gateway. If you contact us on any channel, we receive the contents of those messages.', '2', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO privacy_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('3', 'Information We Do Not Receive', 'To run and secure the website we also collect basic technical information: your IP address, browser and device type, approximate location derived from your IP, and your login-session activity (including the vehicles you view and the reports or invoices you download). We do not access your contact list, files, or any data beyond what you submit and what your browser sends with each request.', '3', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO privacy_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('5', 'How We Use Your Information', 'We use your data to deliver the reports you request, to verify your login and secure your account, to process payments and issue GST invoices, to communicate with you about the service (OTPs, transaction confirmations and support — by SMS, email or WhatsApp), to maintain records required under tax and accounting law, and to monitor for abuse and fraud.', '5', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO privacy_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('7', 'Data Sharing', 'We do not sell, rent or trade your personal data. It is shared only with the parties necessary to run the service: our payment gateway for transactions, our SMS, email and messaging providers (including WhatsApp / Meta where used) for communicating with you, the authorized vehicle-data API providers for retrieving records, and our hosting and infrastructure providers.', '7', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO privacy_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('14', 'Data on WhatsApp', 'When you use GaadiPe on WhatsApp, your messages and phone number are processed through Meta Platforms to deliver the service. We store your WhatsApp number, profile name, the vehicles you check, and the chat interactions needed to provide reports, payments, monitoring and support.', '14', 't', '2026-08-24 16:02:12.482158+05:30', '2026-08-24 16:02:12.482158+05:30', '1.0', '2026-08-24') ON CONFLICT (id) DO NOTHING;
INSERT INTO privacy_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('15', 'Monitoring Data', 'For vehicles you place under trial or Premium monitoring, we periodically retrieve and store Government-sourced vehicle data (challans, insurance, PUCC, fitness, tax) for the duration of the plan so we can alert you to changes. You can stop monitoring at any time, after which we cease these checks.', '15', 't', '2026-08-24 16:02:12.482158+05:30', '2026-08-24 16:02:12.482158+05:30', '1.0', '2026-08-24') ON CONFLICT (id) DO NOTHING;
INSERT INTO privacy_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('17', 'Number Plates in Our Game', 'GaadiPe runs a number-plate game. To power it we use only publicly-visible vehicle number plates together with their State, RTO city and broad vehicle type (for example car or two-wheeler). No owner name, address, contact, documents, insurance, challans, FASTag or any other report detail is ever included in the game. A plate shown in the game is used anonymously and is never linked to any customer, nor to who looked it up. You can ask us to exclude a specific plate at any time.', '17', 't', '2026-08-24 16:02:12.502664+05:30', '2026-08-24 16:02:12.502664+05:30', '1.0', '2026-08-24') ON CONFLICT (id) DO NOTHING;
INSERT INTO privacy_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('18', 'How We Improve GaadiPe', 'We may use anonymised and aggregated information — such as number plates, RTO references and vehicle types stripped of any personal detail — to build, run and improve features like the number-plate game, and to measure and improve the service. This anonymised information cannot reasonably be used to identify you.', '18', 't', '2026-08-24 16:02:12.502664+05:30', '2026-08-24 16:02:12.502664+05:30', '1.0', '2026-08-24') ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS refund_policy (
    id smallint NOT NULL,
    title character varying(255) NOT NULL,
    description text NOT NULL,
    display_order smallint NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    modified_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    version character varying(20) DEFAULT '1.0'::character varying NOT NULL,
    effective_from date DEFAULT CURRENT_DATE NOT NULL
);
ALTER TABLE refund_policy DROP CONSTRAINT IF EXISTS refund_policy_pkey;
ALTER TABLE refund_policy ADD CONSTRAINT refund_policy_pkey PRIMARY KEY (id);
INSERT INTO refund_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('2', 'When a Refund Is Granted', 'A full refund is issued where payment was deducted but no report was delivered, where a duplicate payment was made for the same report, or where the report delivered was materially incomplete or corrupted due to a fault on our side.', '2', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO refund_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('3', 'When a Refund Is Not Granted', 'Refunds are not available merely because the Government record shows information you did not expect, because a record is outdated or missing at source, because you entered an incorrect vehicle number, or because you changed your mind after delivery. The accuracy of Government data is outside our control.', '3', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO refund_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('4', 'Failed or Pending Payments', 'If an amount is debited but the transaction fails, the payment gateway usually reverses it automatically within the bank''s standard cycle. If the amount is not credited back within that period, raise a refund request with your transaction reference and we will pursue it with the gateway.', '4', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO refund_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('6', 'Processing Time', 'Approved refunds are initiated within 3 business days of approval and are credited back to the original payment method. Depending on your bank or UPI provider, the credit typically appears within 5 to 7 business days after initiation.', '6', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO refund_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('7', 'Chargebacks', 'Please contact us before raising a chargeback with your bank. Chargebacks raised without first giving us an opportunity to resolve the issue may result in suspension of access pending investigation.', '7', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO refund_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('1', 'Nature of the Product', 'GaadiPe sells digital reports that are generated and delivered instantly on payment. Because the product is consumed the moment it is delivered, paid reports are generally non-refundable once successfully delivered.', '1', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO refund_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('5', 'How to Request a Refund', 'Send a refund request by email to support@gaadipe.in (or on any support channel we offer, including WhatsApp) within 7 days of the transaction. Include the registered mobile number, the vehicle number, the payment/transaction reference and a brief description of the issue.', '5', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO refund_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('8', 'Trials and Subscriptions', 'The 7-day trial is free, so no refund applies to it. For a paid Premium term, contact support: because Premium activates immediately and begins consuming paid data lookups and monitoring, refunds are considered case by case, and any full report or monitoring already delivered may be non-refundable.', '8', 't', '2026-08-24 16:02:12.482158+05:30', '2026-08-24 16:02:12.482158+05:30', '1.0', '2026-08-24') ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS liability_policy (
    id smallint NOT NULL,
    title character varying(255) NOT NULL,
    description text NOT NULL,
    display_order smallint NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    modified_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    version character varying(20) DEFAULT '1.0'::character varying NOT NULL,
    effective_from date DEFAULT CURRENT_DATE NOT NULL
);
ALTER TABLE liability_policy DROP CONSTRAINT IF EXISTS liability_policy_pkey;
ALTER TABLE liability_policy ADD CONSTRAINT liability_policy_pkey PRIMARY KEY (id);
INSERT INTO liability_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('3', 'No Advice', 'Nothing in a report constitutes legal, financial, insurance or purchase advice. Any decision to buy, sell, insure, finance or operate a vehicle is your own, and you should independently verify original documents and physically inspect the vehicle before deciding.', '3', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO liability_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('4', 'Limitation of Liability', 'To the maximum extent permitted by law, the total liability of ServerPe App Solutions arising out of or in connection with the service shall not exceed the amount actually paid by you for the specific report giving rise to the claim. We are not liable for indirect, incidental, special, punitive or consequential losses, including loss of profit, loss of opportunity or loss of data.', '4', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO liability_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('7', 'Indemnity', 'You agree to indemnify and hold harmless ServerPe App Solutions, its proprietors and personnel against any claim, demand, loss or expense arising from your misuse of the service, your breach of these policies, or your violation of any law or third-party right.', '7', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO liability_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('8', 'Force Majeure', 'We shall not be held liable for any failure or delay in performance caused by events beyond our reasonable control, including natural disasters, acts of Government, changes in law, network or power failures, cyber-attacks, or upstream service withdrawal.', '8', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO liability_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('12', 'The Game', 'The number-plate game is provided for engagement only. GaadiPe is not liable for the game''s availability or outcomes, and rewards are limited to discounts on GaadiPe Premium.', '12', 't', '2026-08-24 16:02:12.482158+05:30', '2026-08-24 16:02:12.482158+05:30', '1.0', '2026-08-24') ON CONFLICT (id) DO NOTHING;
INSERT INTO liability_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('1', 'Informational Purpose Only', 'Reports generated by GaadiPe are for information and personal due-diligence purposes only. They are not legal documents, not proof of ownership, not a valuation, not a certificate of roadworthiness, and must not be submitted to any authority as an official record.', '1', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO liability_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('5', 'Transactions Between Users and Third Parties', 'GaadiPe is not a party to any vehicle sale, purchase, financing, insurance or transfer transaction. We accept no liability for disputes, losses or damages arising from any transaction you enter into, whether or not a GaadiPe report was consulted.', '5', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO liability_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('2', 'Third-Party Data Disclaimer', 'All vehicle information originates from Government systems accessed through ULIP and is served from Government backup/replica databases rather than the live RTO counter system. GaadiPe reproduces this data as received and makes no representation or warranty as to its accuracy, completeness, currency or fitness for any purpose. Errors, omissions, synchronisation delays or divergence between the replica and the RTO''s live record are outside our control, and we accept no liability arising from them.', '2', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 21:05:35.265254+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO liability_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('9', 'Mismatch with RTO Records', 'GaadiPe accepts no liability for any loss, cost, dispute or decision arising from a difference between the data shown in a report and the record held by the Regional Transport Office or any other Government authority. Reports are a starting point for due diligence, not a substitute for it: before buying, selling, insuring or financing a vehicle, verify the particulars with the local RTO and inspect the original documents and the vehicle itself.', '9', 't', '2026-08-13 21:05:35.265254+05:30', '2026-08-13 21:05:35.265254+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO liability_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('10', 'Not a Government Service', 'GaadiPe does not act for, represent, or exercise any authority of any Government body. It cannot issue, amend, renew, cancel or certify any registration, insurance, permit, fitness, emission or challan record. Any action requiring Government authority must be pursued directly with the concerned Regional Transport Office or issuing authority.', '10', 't', '2026-08-13 21:06:55.237073+05:30', '2026-08-13 21:06:55.237073+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO liability_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('6', 'Service Interruptions', 'We are not liable for any loss arising from unavailability, suspension, delay or degradation of the service, including outages of Government or third-party data APIs, payment gateways, hosting infrastructure, or any communication channel (SMS, email or WhatsApp).', '6', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO liability_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('11', 'Monitoring and Alerts', 'Monitoring and alerts are provided on a best-effort basis and depend on third-party and Government-sourced data that may be delayed, incomplete or unavailable. GaadiPe is not liable for any missed, delayed or inaccurate alert, or for any decision made in reliance on one. Always confirm critical matters with the RTO or the relevant authority.', '11', 't', '2026-08-24 16:02:12.482158+05:30', '2026-08-24 16:02:12.482158+05:30', '1.0', '2026-08-24') ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS consent_policy (
    id smallint NOT NULL,
    title character varying(255) NOT NULL,
    description text NOT NULL,
    display_order smallint NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    modified_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    version character varying(20) DEFAULT '1.0'::character varying NOT NULL,
    effective_from date DEFAULT CURRENT_DATE NOT NULL
);
ALTER TABLE consent_policy DROP CONSTRAINT IF EXISTS consent_policy_pkey;
ALTER TABLE consent_policy ADD CONSTRAINT consent_policy_pkey PRIMARY KEY (id);
INSERT INTO consent_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('4', 'Consent to Process Payments', 'For paid reports, you consent to your transaction details being shared with our payment gateway partner in order to process the payment and to generate a GST-compliant invoice in your name.', '4', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO consent_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('7', 'Data Deletion Request', 'You may request deletion of your personal data at any time. On verification of your identity we will delete or anonymise your conversation history, stored profile and report records, except where retention is required under tax, accounting or other applicable law.', '7', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO consent_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('8', 'Record of Consent', 'We maintain a record of the consents you give, including what was agreed and when, so that both you and we have an accurate account of the basis on which your data is processed.', '8', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO consent_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('2', 'Consent to Retrieve Vehicle Data', 'By sending a vehicle registration number you request and consent to GaadiPe retrieving that vehicle''s records from Government sources on your behalf, and confirm that you have a lawful and legitimate reason for checking that vehicle.', '2', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO consent_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('5', 'Purpose Limitation', 'You confirm that data obtained through GaadiPe will be used only for your own lawful purposes and will not be resold, redistributed, published, or used to contact, profile, trace or harass any vehicle owner.', '5', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO consent_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('1', 'Consent to Communicate', 'You consent to receive service communications from GaadiPe — including one-time passwords, reports, transaction confirmations, service notifications and support responses — on the mobile number and email you provide. These may be sent by SMS, email and, now or in the future, WhatsApp or other messaging channels. You may opt out of non-essential messages at any time; essential transactional messages (such as OTP and payment confirmations) are required to provide the service.', '1', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO consent_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('3', 'Consent to Store Data', 'You consent to GaadiPe storing your mobile number, name, login and device/session information, communication history, and the vehicle records retrieved for you, for the purposes and durations described in the privacy policy.', '3', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO consent_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('6', 'Withdrawal of Consent', 'You may withdraw your consent at any time by emailing support@gaadipe.in (or via any support channel we offer). On withdrawal we will stop processing your data for the affected purposes, though we may retain records we are legally required to keep.', '6', 't', '2026-08-13 20:34:46.470396+05:30', '2026-08-13 20:34:46.470396+05:30', '1.0', '2026-08-13') ON CONFLICT (id) DO NOTHING;
INSERT INTO consent_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('9', 'Consent to Monitor Your Vehicle', 'By starting a trial or buying Premium for a vehicle, you authorise GaadiPe to periodically retrieve that vehicle''s Government-sourced data and to send you related alerts on WhatsApp for the plan''s duration. You can withdraw this at any time by asking us to stop, after which monitoring and alerts cease.', '9', 't', '2026-08-24 16:02:12.482158+05:30', '2026-08-24 16:02:12.482158+05:30', '1.0', '2026-08-24') ON CONFLICT (id) DO NOTHING;
INSERT INTO consent_policy (id, title, description, display_order, is_active, created_at, modified_at, version, effective_from) VALUES ('10', 'Consent to Marketing Messages', 'With your opt-in, we may send occasional promotional WhatsApp messages such as offers or game reminders. You can opt out of these at any time without affecting essential service messages like payment confirmations and alerts you have subscribed to.', '10', 't', '2026-08-24 16:02:12.482158+05:30', '2026-08-24 16:02:12.482158+05:30', '1.0', '2026-08-24') ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS cancellation_policy (
    id smallint NOT NULL,
    title character varying(255) NOT NULL,
    description text NOT NULL,
    display_order smallint NOT NULL,
    version character varying(20) DEFAULT '1.0'::character varying NOT NULL,
    effective_from date DEFAULT CURRENT_DATE NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    modified_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
ALTER TABLE cancellation_policy DROP CONSTRAINT IF EXISTS cancellation_policy_pkey;
ALTER TABLE cancellation_policy ADD CONSTRAINT cancellation_policy_pkey PRIMARY KEY (id);
INSERT INTO cancellation_policy (id, title, description, display_order, version, effective_from, is_active, created_at, modified_at) VALUES ('1', 'Before Payment', 'You may abandon a report request at any time before payment simply by not completing the transaction. Nothing is charged until payment succeeds, and no cancellation request is needed.', '1', '1.0', '2026-08-13', 't', '2026-08-13 21:06:55.237073+05:30', '2026-08-13 21:06:55.237073+05:30') ON CONFLICT (id) DO NOTHING;
INSERT INTO cancellation_policy (id, title, description, display_order, version, effective_from, is_active, created_at, modified_at) VALUES ('2', 'After Payment', 'Because reports are generated and delivered instantly on successful payment, an order cannot be cancelled once the report has been delivered. If payment succeeded but no report was delivered, treat it as a refund case under the Refund Policy.', '2', '1.0', '2026-08-13', 't', '2026-08-13 21:06:55.237073+05:30', '2026-08-13 21:06:55.237073+05:30') ON CONFLICT (id) DO NOTHING;
INSERT INTO cancellation_policy (id, title, description, display_order, version, effective_from, is_active, created_at, modified_at) VALUES ('4', 'Recurring Plans', 'Where a subscription or validity-based plan is offered, you may cancel renewal at any time before the renewal date. Cancellation stops future charges; it does not refund the current period already availed.', '4', '1.0', '2026-08-13', 't', '2026-08-13 21:06:55.237073+05:30', '2026-08-13 21:06:55.237073+05:30') ON CONFLICT (id) DO NOTHING;
INSERT INTO cancellation_policy (id, title, description, display_order, version, effective_from, is_active, created_at, modified_at) VALUES ('3', 'Cancellation by GaadiPe', 'We may cancel and refund an order if the vehicle number is invalid, if the Government source is unavailable and the report cannot be generated, or if we reasonably suspect fraud or misuse. Any amount already collected for a cancelled order is refunded in full.', '3', '1.0', '2026-08-13', 't', '2026-08-13 21:06:55.237073+05:30', '2026-08-13 21:06:55.237073+05:30') ON CONFLICT (id) DO NOTHING;
INSERT INTO cancellation_policy (id, title, description, display_order, version, effective_from, is_active, created_at, modified_at) VALUES ('5', 'Stopping Premium or Monitoring', 'There is no auto-renewal, so you are never charged automatically. To stop before a term ends, message us and we will deactivate monitoring for that vehicle; otherwise the plan ends on its own at the close of its 28-day term.', '5', '1.0', '2026-08-24', 't', '2026-08-24 16:02:12.482158+05:30', '2026-08-24 16:02:12.482158+05:30') ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS delivery_policy (
    id smallint NOT NULL,
    title character varying(255) NOT NULL,
    description text NOT NULL,
    display_order smallint NOT NULL,
    version character varying(20) DEFAULT '1.0'::character varying NOT NULL,
    effective_from date DEFAULT CURRENT_DATE NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    modified_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
ALTER TABLE delivery_policy DROP CONSTRAINT IF EXISTS delivery_policy_pkey;
ALTER TABLE delivery_policy ADD CONSTRAINT delivery_policy_pkey PRIMARY KEY (id);
INSERT INTO delivery_policy (id, title, description, display_order, version, effective_from, is_active, created_at, modified_at) VALUES ('4', 'Non-Delivery', 'If a paid report cannot be delivered at all, the amount is refunded in full under the Refund Policy. You are never charged twice for the same undelivered report.', '4', '1.0', '2026-08-13', 't', '2026-08-13 21:06:55.237073+05:30', '2026-08-13 21:06:55.237073+05:30') ON CONFLICT (id) DO NOTHING;
INSERT INTO delivery_policy (id, title, description, display_order, version, effective_from, is_active, created_at, modified_at) VALUES ('5', 'Report Validity', 'Each report reflects the Government record as at the moment of generation, and remains accessible for the validity period stated in your plan. Data can change at source at any time after generation.', '5', '1.0', '2026-08-13', 't', '2026-08-13 21:06:55.237073+05:30', '2026-08-13 21:06:55.237073+05:30') ON CONFLICT (id) DO NOTHING;
INSERT INTO delivery_policy (id, title, description, display_order, version, effective_from, is_active, created_at, modified_at) VALUES ('1', 'Digital Delivery Only', 'GaadiPe sells digital information reports. Nothing is physically shipped. No courier, shipping charge, tracking number or delivery address is involved at any stage.', '1', '1.0', '2026-08-13', 't', '2026-08-13 21:06:55.237073+05:30', '2026-08-13 21:06:55.237073+05:30') ON CONFLICT (id) DO NOTHING;
INSERT INTO delivery_policy (id, title, description, display_order, version, effective_from, is_active, created_at, modified_at) VALUES ('2', 'How and When You Receive It', 'Reports are generated instantly and made available to download on gaadipe.in immediately after successful payment, together with your GST invoice. Where applicable we may also send a link or copy to your registered mobile or email (including via WhatsApp, where offered).', '2', '1.0', '2026-08-13', 't', '2026-08-13 21:06:55.237073+05:30', '2026-08-13 21:06:55.237073+05:30') ON CONFLICT (id) DO NOTHING;
INSERT INTO delivery_policy (id, title, description, display_order, version, effective_from, is_active, created_at, modified_at) VALUES ('3', 'Delivery Delays', 'Delivery may be delayed if a Government or data-source system is slow or temporarily down. Your reports and invoice always remain available to download from gaadipe.in under your logged-in session. If a paid report has not appeared within 30 minutes, contact support with your transaction reference.', '3', '1.0', '2026-08-13', 't', '2026-08-13 21:06:55.237073+05:30', '2026-08-13 21:06:55.237073+05:30') ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS data_deletion_policy (
    id smallint NOT NULL,
    title character varying(255) NOT NULL,
    description text NOT NULL,
    display_order smallint NOT NULL,
    version character varying(20) DEFAULT '1.0'::character varying NOT NULL,
    effective_from date DEFAULT CURRENT_DATE NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    modified_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
ALTER TABLE data_deletion_policy DROP CONSTRAINT IF EXISTS data_deletion_policy_pkey;
ALTER TABLE data_deletion_policy ADD CONSTRAINT data_deletion_policy_pkey PRIMARY KEY (id);
INSERT INTO data_deletion_policy (id, title, description, display_order, version, effective_from, is_active, created_at, modified_at) VALUES ('4', 'What We Must Retain', 'Payment, invoice and tax records are retained for the period required under Indian tax and accounting law, even after a deletion request. Anonymised and aggregated statistics that cannot identify you may also be retained. Vehicle records themselves originate from Government systems and continue to exist there independently of us.', '4', '1.0', '2026-08-13', 't', '2026-08-13 21:06:55.237073+05:30', '2026-08-13 21:06:55.237073+05:30') ON CONFLICT (id) DO NOTHING;
INSERT INTO data_deletion_policy (id, title, description, display_order, version, effective_from, is_active, created_at, modified_at) VALUES ('6', 'Effect of Deletion', 'Deletion is irreversible. Previously delivered reports and your conversation history cannot be recovered afterwards, and starting again means a fresh request and, for paid plans, a fresh payment.', '6', '1.0', '2026-08-13', 't', '2026-08-13 21:06:55.237073+05:30', '2026-08-13 21:06:55.237073+05:30') ON CONFLICT (id) DO NOTHING;
INSERT INTO data_deletion_policy (id, title, description, display_order, version, effective_from, is_active, created_at, modified_at) VALUES ('1', 'Your Right to Deletion', 'You may ask us to delete the personal data we hold about you at any time, without giving a reason. This covers your profile, your login and communication history with us, and the association between you and the vehicles you have checked.', '1', '1.0', '2026-08-13', 't', '2026-08-13 21:06:55.237073+05:30', '2026-08-13 21:06:55.237073+05:30') ON CONFLICT (id) DO NOTHING;
INSERT INTO data_deletion_policy (id, title, description, display_order, version, effective_from, is_active, created_at, modified_at) VALUES ('2', 'How to Request Deletion', 'Email your deletion request to support@gaadipe.in from your registered email, or from the mobile number you used with the service (including via any support channel we offer, such as WhatsApp). We verify that the request genuinely comes from you before acting on it.', '2', '1.0', '2026-08-13', 't', '2026-08-13 21:06:55.237073+05:30', '2026-08-13 21:06:55.237073+05:30') ON CONFLICT (id) DO NOTHING;
INSERT INTO data_deletion_policy (id, title, description, display_order, version, effective_from, is_active, created_at, modified_at) VALUES ('3', 'What Gets Deleted', 'Your user profile, login sessions and communication history, activity and device records, and stored report associations are deleted or irreversibly anonymised.', '3', '1.0', '2026-08-13', 't', '2026-08-13 21:06:55.237073+05:30', '2026-08-13 21:06:55.237073+05:30') ON CONFLICT (id) DO NOTHING;
INSERT INTO data_deletion_policy (id, title, description, display_order, version, effective_from, is_active, created_at, modified_at) VALUES ('5', 'Timeline', 'Verified deletion requests are actioned within 30 days. We confirm by email (or another channel you provide) once the deletion is complete.', '5', '1.0', '2026-08-13', 't', '2026-08-13 21:06:55.237073+05:30', '2026-08-13 21:06:55.237073+05:30') ON CONFLICT (id) DO NOTHING;
INSERT INTO data_deletion_policy (id, title, description, display_order, version, effective_from, is_active, created_at, modified_at) VALUES ('7', 'Monitoring and Game Data', 'On deletion we also remove your active monitoring subscriptions and your game play history, scores and any unredeemed rewards, and we stop all alerts.', '7', '1.0', '2026-08-24', 't', '2026-08-24 16:02:12.482158+05:30', '2026-08-24 16:02:12.482158+05:30') ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS business_details (
    id smallint NOT NULL,
    business_name character varying(200) NOT NULL,
    legal_entity_type character varying(100),
    gstin character varying(20),
    registered_address text,
    city character varying(100),
    state character varying(100),
    pincode character varying(10),
    country character varying(100) DEFAULT 'India'::character varying NOT NULL,
    support_email character varying(150),
    support_phone character varying(20),
    whatsapp_number character varying(20),
    website_url character varying(200),
    grievance_officer_name character varying(150),
    grievance_officer_email character varying(150),
    grievance_officer_phone character varying(20),
    grievance_response_days smallint DEFAULT 30 NOT NULL,
    logo_path text,
    signature_path text,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    modified_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    home_state character varying(100) DEFAULT 'Karnataka'::character varying NOT NULL,
    home_state_code character varying(5) DEFAULT '29'::character varying NOT NULL,
    company_tagline character varying(200),
    company_website character varying(200),
    product_name character varying(100),
    product_tagline character varying(200),
    product_website character varying(200),
    product_support_email character varying(150),
    proprietor_name character varying(150),
    pan character varying(20),
    gst_state_code character varying(5),
    grievance_officer_designation character varying(150),
    grievance_response_hours smallint DEFAULT 24,
    grievance_resolution_days smallint DEFAULT 15,
    consent_prompt text DEFAULT 'I have read and agree to all of GaadiPe''s Terms, Policies and Consents, including how my data is used and how GaadiPe communicates with me.'::text,
    purpose_declaration text DEFAULT 'I confirm that this vehicle and its owner are known to me, and that I am requesting these details for a lawful and legitimate purpose. I take full responsibility for the use of this information.'::text,
    purpose_declaration_doc text DEFAULT 'Requester''s declaration: the requester confirmed that this vehicle and its owner are known to them and that these details were requested for a lawful, legitimate purpose, taking full responsibility for their use.'::text
);
ALTER TABLE business_details DROP CONSTRAINT IF EXISTS business_details_pkey;
ALTER TABLE business_details ADD CONSTRAINT business_details_pkey PRIMARY KEY (id);
INSERT INTO business_details (id, business_name, legal_entity_type, gstin, registered_address, city, state, pincode, country, support_email, support_phone, whatsapp_number, website_url, grievance_officer_name, grievance_officer_email, grievance_officer_phone, grievance_response_days, logo_path, signature_path, is_active, created_at, modified_at, home_state, home_state_code, company_tagline, company_website, product_name, product_tagline, product_website, product_support_email, proprietor_name, pan, gst_state_code, grievance_officer_designation, grievance_response_hours, grievance_resolution_days, consent_prompt, purpose_declaration, purpose_declaration_doc) VALUES ('1', 'ServerPe App Solutions', 'Proprietorship', '29BSMPK7696H1ZT', 'The Orchard, HMT watch factory main road, HMT estate, Jalahalli, Bangalore - 560013', 'Bangalore', 'Karnataka', '560013', 'India', 'support@gaadipe.in', NULL, '+916363271302', 'https://gaadipe.in', 'Shivakumar', 'support@gaadipe.in', NULL, '30', NULL, NULL, 't', '2026-08-13 21:06:55.237073+05:30', '2026-08-13 22:54:30.890711+05:30', 'Karnataka', '29', 'Smart clicks, Smart taps', 'serverpe.in', 'GaadiPe', 'Har gaadi ki kundli.', 'gaadipe.in', 'support@gaadipe.in', 'Shivakumar Kirigeri', 'BSMPK7696H', '29', 'Proprietor & Grievance Officer', '24', '15', 'I have read and agree to all of GaadiPe''s Terms, Policies and Consents, including how my data is used and how GaadiPe communicates with me.', 'I confirm that this vehicle and its owner are known to me, and that I am requesting these details for a lawful and legitimate purpose. I take full responsibility for the use of this information.', 'Requester''s declaration: the requester confirmed that this vehicle and its owner are known to them and that these details were requested for a lawful, legitimate purpose, taking full responsibility for their use.') ON CONFLICT (id) DO NOTHING;
